version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gctx
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: 
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- .Arch }}
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

project_name: gctx

homebrew_casks:
  - repository:
      owner: k0wl0n
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    commit_author:
      name: k0wl0n
      email: wahyuanggana1@gmail.com
    homepage: "https://github.com/k0wl0n/gctx"
    description: "GCloud Multi-Account Manager (Go + Cobra)"
    license: "MIT"
    directory: Formula

scoops:
  - repository:
      owner: k0wl0n
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"
    commit_author:
      name: k0wl0n
      email: wahyuanggana1@gmail.com
    homepage: "https://github.com/k0wl0n/gctx"
    description: "GCloud Multi-Account Manager (Go + Cobra)"
    license: "MIT"
