name: Bug Report
description: Create a report to help us improve gctx
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I encountered an issue when...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. See error '...'
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: [e.g. macOS, Windows, Linux]
        - gctx version: [e.g. v0.1.0]
        - gcloud version: [e.g. 450.0.0]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output.
      render: shell
